# Credenciales para el envio de correos
smtp.user=20253ds069@utez.edu.mx
smtp.pass=xhvc uahx ldey lyry

# Credenciales de Base de Datos Oracle
db.user=ADMIN
db.pass=Contasena213546
db.name=integradora1_high